# Generated by Django 4.0.4 on 2022-05-24 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_text', models.CharField(max_length=50)),
                ('coach', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=100)),
                ('s_phone', models.CharField(max_length=20)),
                ('s_email', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.team')),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=100)),
                ('d_email', models.CharField(max_length=100)),
                ('d_phone', models.CharField(max_length=20)),
                ('d_address', models.CharField(max_length=200)),
                ('d_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.student')),
            ],
        ),
    ]
