# Generated by Django 4.0.5 on 2022-07-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_zip',
            field=models.CharField(max_length=10),
        ),
    ]
