# Generated by Django 4.0.4 on 2022-05-25 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='d_address',
            new_name='donor_address',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='d_email',
            new_name='donor_email',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='d_name',
            new_name='donor_name',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='d_phone',
            new_name='donor_phone',
        ),
        migrations.RenameField(
            model_name='donor',
            old_name='d_student',
            new_name='donor_student',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_email',
            new_name='student_email',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_name',
            new_name='student_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='s_phone',
            new_name='student_phone',
        ),
    ]
