# Generated by Django 4.1 on 2023-07-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
