# Generated by Django 4.1 on 2023-08-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_donor_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='roster',
            name='pref_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='StudentInfo',
        ),
    ]
