# Generated by Django 4.1 on 2023-08-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_roster_pref_name_delete_studentinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roster',
            name='pref_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
