# Generated by Django 4.0.4 on 2022-06-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_student_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donor_city',
            field=models.CharField(default='Hays', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donor',
            name='donor_state',
            field=models.CharField(default='Kansas', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='pref_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
