# Generated by Django 4.0.4 on 2022-06-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_donor_donor_city_donor_donor_state_student_pref_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=100)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.team')),
            ],
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pref_name', models.CharField(max_length=20, null=True)),
                ('student_phone', models.CharField(max_length=20, null=True)),
                ('student_email', models.CharField(max_length=100, null=True)),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.roster')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.team')),
            ],
        ),
        migrations.AlterField(
            model_name='donor',
            name='donor_student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact.studentinfo'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
