# Generated by Django 4.1 on 2024-10-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contacts_members_project_remove_roster_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_link',
            field=models.URLField(blank=True),
        ),
    ]
