# Generated by Django 4.1 on 2024-10-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_project_project_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='project_group',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
