# Generated by Django 4.0.4 on 2022-06-08 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_roster_studentinfo_alter_donor_donor_student_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roster',
            old_name='student',
            new_name='student_name',
        ),
    ]
